'use strict';

module.exports = {
  datauri: 'base64',
  js2svg: {
    indent: 2,
    pretty: true,
  },
  multipass: false,
  plugins: [
    { name: 'cleanupAttrs', active: false },
    { name: 'mergeStyles', active: true },
    { name: 'inlineStyles', active: false },
    { name: 'removeDoctype', active: true },
    { name: 'removeXMLProcInst', active: true },
    { name: 'removeComments', active: true },
    { name: 'removeMetadata', active: true },
    { name: 'removeTitle', active: true },
    { name: 'removeDesc', active: true },
    { name: 'removeUselessDefs', active: true },
    { name: 'removeXMLNS', active: true },
    { name: 'removeEditorsNSData', active: true },
    { name: 'removeEmptyAttrs', active: true },
    { name: 'removeHiddenElems', active: true },
    { name: 'removeEmptyText', active: true },
    { name: 'removeEmptyContainers', active: true },
    { name: 'removeViewBox', active: false },
    { name: 'cleanupEnableBackground', active: true },
    { name: 'minifyStyles', active: false },
    { name: 'convertStyleToAttrs', active: false },
    { name: 'convertColors', active: true },
    { name: 'convertPathData', active: true },
    { name: 'convertTransform', active: true },
    { name: 'removeUnknownsAndDefaults', active: true },
    { name: 'removeNonInheritableGroupAttrs', active: true },
    { name: 'removeUselessStrokeAndFill', active: true },
    { name: 'removeUnusedNS', active: true },
    { name: 'prefixIds', active: false },
    { name: 'cleanupIDs', active: true },
    { name: 'cleanupNumericValues', active: true },
    { name: 'cleanupListOfValues', active: true },
    { name: 'moveElemsAttrsToGroup', active: true },
    { name: 'moveGroupAttrsToElems', active: false },
    { name: 'collapseGroups', active: true },
    { name: 'removeRasterImages', active: false },
    { name: 'mergePaths', active: true },
    { name: 'convertShapeToPath', active: false },
    { name: 'convertEllipseToCircle', active: true },
    { name: 'sortAttrs', active: false },
    { name: 'sortDefsChildren', active: true },
    { name: 'removeDimensions', active: true },
    { name: 'removeAttrs', active: true },
    { name: 'removeAttributesBySelector', active: false },
    { name: 'removeElementsByAttr', active: false },
    { name: 'addClassesToSVGElement', active: false },
    { name: 'addAttributesToSVGElement', active: false },
    { name: 'removeOffCanvasPaths', active: true },
    { name: 'removeStyleElement', active: true },
    { name: 'removeScriptElement', active: true },
    { name: 'reusePaths', active: false },
  ],
};
